name: Clone Private Repo

on:
  push:
    paths:
     - .github/workflows/clone.yml
  
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ORG_GH_APPS_ID }}
          private-key: ${{ secrets.ORG_GH_APPS_PRIVATE_TOKEN }}
          owner: Orgcongembed
          
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: Orgcongembed/test_gh_apps
          ref: main

    # - name: Checkout this repository
    #   uses: actions/checkout@v4
      
    # - name: Clone private repository
    #   env:
    #     GH_PAT: ${{ secrets.MY_CLASSIC_TOKEN }}
    #   run: |
    #     git clone https://$GH_PAT@github.com/congneb/test_build.git
