name: Build and Push Docker Image

on:
  push:
    paths:
      - .github/workflows/docker_pull.yml
  workflow_dispatch:
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull Docker Image
        run: docker pull congneb/test_1:v1
        
      - name: Run Docker Container
        run: docker run congneb/test_1:v1

      - name: Other
        run: |
          mkdir pr_check
          docker run -d --name temp_container congneb/test_1:v1
          # docker cp temp_container:/path/to/file/on/container pr_check
          docker cp temp_container:. pr_check

          ls pr_check
          echo =====================================
          ls pr_check/usr/src/app
          echo =====================================
          
          docker stop temp_container
          docker rm temp_container

          echo =====================================
          ls pr_check
          
