name: Build and Push Docker Image

on:
  push:
    paths:
      - .github/workflows/docker.yml
  workflow_dispatch:
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/test_1:v1
      # tags: <your_dockerhub_username>/<your_image_name>:<tag>

      # - name: Pull Docker Image
      #   run: docker pull ${{ secrets.DOCKER_USERNAME }}/test_1:v1
      # - name: Run Docker Container
      #   run: docker run ${{ secrets.DOCKER_USERNAME }}/test_1:v1
