name: Check push event of other repo

on:
  push:
    paths:
     - .github/workflows/manual.yml

jobs:
  check-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check push event
        run: |
          curl -X GET \
          https://api.github.com/repos/congembed/test_gh_apps/events \
          -H 'Authorization: Bearer ${{ secrets.MY_CLASSIC_TOKEN }}' \
          -H 'Content-Type: application/json'
          
          if [ $? -eq 0 ]; then
            echo "Push event detected from other repository"
          else
            echo "Push event not detected from other repository"
          fi
