name: CI
on: 
  push:
   paths:
    - .github/workflows/manual.yml

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: Install some env
      # if: always()
      run : |
        sudo apt-get install git-lfs -y
        git lfs install --skip-repo

    - name: checkout arduino repo
      # if: always()
      uses: actions/checkout@v4
      with:
        repository: 'congneb/Cpp-Project'

    - run: |
        curl -u congneb:${{ secrets.MY_CLASSIC_TOKEN }} \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/STM32-Basic/statuses/${{ github.sha }} \
          -d '{
            "state": "success",
            "target_url": "https://www.free4talk.com/",
            "description": "Details hidden",
            "context": "hahai"
          }'
