
name: Trigger Other Workflow

on:
  push:
    paths:
     - .github/workflows/manual.yml

  workflow_dispatch:

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Workflow in Another Repository
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.MY_PAT_TOKEN }}" \
            https://api.github.com/repos/congembed/test_gh_apps/dispatches \
            -d '{"event_type":"run-workflow","client_payload":{}}'



        
          # curl -X GET \
          # https://api.github.com/repos/congembed/test_gh_apps/events \
          # -H 'Authorization: Bearer ${{ secrets.MY_CLASSIC_TOKEN }}' \
          # -H 'Content-Type: application/json'
          
          # if [ $? -eq 0 ]; then
          #   echo "Push event detected from other repository"
          # else
          #   echo "Push event not detected from other repository"
          # fi
