name: CI
on: 
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: Install some env
      if: always()
      run : |
        sudo apt-get install git-lfs -y
        git lfs install --skip-repo

    - name: checkout arduino repo
      if: always()
      uses: actions/checkout@v4
      with:
        repository: 'congneb/Cpp-Project'

    - run: |
        ls .
        echo Hahahahaha
