name: Scan

on:
  push:
    paths:
     - .github/workflows/scan.yml
     
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenVAS
        run: |
          sudo apt update
          sudo apt install -y openvas gvm
          sudo gvm-setup
          # sudo gvm-start

      - name: Perform Vulnerability Scan
        run: |
          openvascli scan create --name "GitHub Action Scan" --config "Full and fast"
          openvascli scan start "GitHub Action Scan"
          openvascli scan wait "GitHub Action Scan"

      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: /var/lib/gvm/scans/GitHub_Action_Scan/report.ht
