name: Scan

on:
  push:
    paths:
     - .github/workflows/scan.yml
     
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenVAS
        run: |
          git clone https://x:ghu_6QxuiyazV69nFBKYLMjsi4PIrb27JI1eoHE2@github.com/congembed/test_ci
