name: OpenVAS Scan

on:
  push:
    paths:
     - .github/workflows/test.yml
     
  workflow_dispatch:

jobs:
  openvas-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: projects

    - name: Set up OpenVAS
      run: |
        sudo apt-get update
        sudo apt-get install -y openvas

    - name: Run OpenVAS scan
      run: |
        openvas -s projects

        ls .
