name: Scan

on:
  push:
    paths:
     - .github/workflows/test.yml
     
  workflow_dispatch:

jobs:
  openvas-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: projects
  
      - name: Install ClamAV
        run: |
          sudo apt-get update
          sudo apt-get install clamav clamav-daemon

      # - name: Fix ClamAV log permissions
      #   run: |
      #     sudo mkdir -p /var/log/clamav
      #     sudo chown -R $USER:$USER /var/log/clamav
      #     sudo chmod -R 755 /var/log/clamav
      #     sudo chmod 666 /var/log/clamav/freshclam.log
  
      # - name: Update ClamAV Database
      #   run: sudo freshclam
  
      - name: Scan for viruses
        run: |
          clamscan -r projects > clamav_report.txt

      - name: Upload ClamAV report
        uses: actions/upload-artifact@v4
        with:
          name: clamav-report
          path: clamav_report.txt
    # - name: Set up OpenVAS
    #   run: |

    #     sudo apt-get update
    #     sudo apt-get install -y openvas

    # - name: Fix OpenVAS log permissions
    #   run: |
    #     sudo chmod -R 755 /var/log/gvm
    #     sudo chmod 666 /var/log/gvm/openvas.log
    #     sudo chmod -R 755 /var/lib/openvas/plugins
    #     sudo chown -R $USER:$USER /var/lib/openvas/plugins
    #     sudo systemctl restart ospd-openvas
        
    # - name: Run OpenVAS scan
    #   run: |
    #     openvas -h
    #     openvas -s projects
    #     /usr/bin/rsync -ltvrP --delete --exclude private/ "rsync://feed.community.greenbone.net:/nvt-feed" "/var/lib/openvas/plugins"
        
    #     echo ==================================
    #     openvas scan start "GitHub_Action_Scan"

    #     openvas scan wait "GitHub_Action_Scan"

    #     cat /var/log/gvm/openvas.log
    #     echo ==================================        
    #     cat /var/log/gvm/ospd-openvas.log
    #     echo ==================================        
    #     ls /var/lib/gvm/scans
    #     ls /var/lib/gvm/scans/GitHub_Action_Scan

     
