name: Repository Dispatch Workflow

on:
  push:
    paths:
     - .github/workflows/trigger_other_action.yml

permissions:
  contents: write
     
jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ORG_GH_APPS_ID }}
          private-key: ${{ secrets.ORG_GH_APPS_PRIVATE_TOKEN }}
          owner: Orgcongembed
      
      - name: Run Workflow use GH Apps
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ steps.app-token.outputs.token }}" \
            https://api.github.com/repos/Orgcongembed/test_gh_apps/dispatches \
            -d '{"event_type":"run-workflow","client_payload":{"param1": "${{ github.ref }}", "param2": "${{ github.sha }}"}}'


    
      # - name: Run Workflow use PAT token
      #   run: |
      #     curl -X POST \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       -H "Authorization: token ${{ secrets.MY_CLASSIC_TOKEN }}" \
      #       https://api.github.com/repos/congneb/cap1166_sonarqube/dispatches \
      #       -d '{"event_type":"run-workflow","client_payload":{}}'
