name: Build Zephyr Project

on:
  push:
    paths:
      - .github/workflows/zephyr.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: zephyrproject-rtos/example-application
          path: projects
          
      - name: dir
        run: |
          pwd
          ls .
      
      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: projects
          toolchains: arm-zephyr-eabi

      - name: Build Zephyr project
        run: |
          west build -b esp32 projects/app
